package General;


import Utilities.FileHandling;
import Utilities.UserRegistrationInfo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManagerManageOrder extends javax.swing.JFrame {

    UserRegistrationInfo mgr = new UserRegistrationInfo();
      
    private final String POFILE = "pendingOrders.txt";
    private final String COFILE = "completedOrders.txt";
    
    // Create new form "ManagerMenu"
    public ManagerManageOrder(String userID, String userPassword) throws IOException {
        initComponents();
        setContentPane(mainPanel);
        setTitle("APU Cafeteria Ordering System");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        setSize(1080,635); 

        // Set the user ID
        mgr.setUserID(userID);
        mgr.setUserPassword(userPassword);
        userIDTF.setText(userID);

        // Load the menu as soon as the window loads
        loadMenu();
        
        // Set a formatted date and time in the datetime text field
        LocalDateTime dateObj = LocalDateTime.now();
        DateTimeFormatter formatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedDate = dateObj.format(formatObj);
        datetimeTF.setText(formattedDate);
    }

    // To load the menu by putting everything in pendingOrders.txt to pendingOrdersTable
    private void loadMenu() throws IOException {
        DefaultTableModel POTableModel = (DefaultTableModel) pendingOrdersTable.getModel();
        POTableModel.setRowCount(0);
        File file = new File(POFILE);
        try {
            String str;
            BufferedReader br = new BufferedReader(new FileReader(file));
            try {
                while((str = br.readLine()) != null){
                    // Spliting the data into different section using the | delimeter
                    String data[] = str.split("\\|");
                    // Adding the data into the pendingOrdersTable
                    POTableModel.addRow(new Object[]{data[0], data[1], data[2], data[3], data[4], data[5]});
                }
                br.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error: File cannot be read.");
                Logger.error("ManageOrder","Exception occurred - " + e.toString());
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error: File does not exist!");
            Logger.error("ManageOrder","Exception occurred - " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingOrdersTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        userDisplayLabel = new javax.swing.JLabel();
        userIDTF = new javax.swing.JLabel();
        orderCompleteButton = new javax.swing.JButton();
        pendingOrdersLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        datetimeTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(1080, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(244, 244, 244));
        mainPanel.setPreferredSize(new java.awt.Dimension(1080, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setForeground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setBackground(new java.awt.Color(18, 18, 18));
        welcomeLabel.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(18, 18, 18));
        welcomeLabel.setText("Welcome To The APU Cafeteria Ordering System !");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 12, 660, 70));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setForeground(new java.awt.Color(255, 255, 255));
        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingOrdersTable.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        pendingOrdersTable.setForeground(new java.awt.Color(0, 0, 51));
        pendingOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "User ID", "Food ID", "Food", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendingOrdersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingOrdersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pendingOrdersTable);
        if (pendingOrdersTable.getColumnModel().getColumnCount() > 0) {
            pendingOrdersTable.getColumnModel().getColumn(0).setResizable(false);
            pendingOrdersTable.getColumnModel().getColumn(1).setResizable(false);
            pendingOrdersTable.getColumnModel().getColumn(2).setResizable(false);
            pendingOrdersTable.getColumnModel().getColumn(3).setResizable(false);
            pendingOrdersTable.getColumnModel().getColumn(4).setResizable(false);
            pendingOrdersTable.getColumnModel().getColumn(5).setResizable(false);
        }

        tablePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, 870, 370));

        mainPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 191, 870, 320));

        backButton.setBackground(new java.awt.Color(0, 48, 73));
        backButton.setFont(new java.awt.Font("SF Pro Text", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        mainPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 160, 138, 78));

        userPanel.setBackground(new java.awt.Color(255, 255, 255));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userDisplayLabel.setBackground(new java.awt.Color(18, 18, 18));
        userDisplayLabel.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        userDisplayLabel.setForeground(new java.awt.Color(18, 18, 18));
        userDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userDisplayLabel.setText("USER ID");
        userPanel.add(userDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        userIDTF.setBackground(new java.awt.Color(18, 18, 18));
        userIDTF.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        userIDTF.setForeground(new java.awt.Color(0, 102, 155));
        userIDTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIDTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        userPanel.add(userIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 68));

        mainPanel.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, 146, 133));

        orderCompleteButton.setBackground(new java.awt.Color(0, 48, 73));
        orderCompleteButton.setFont(new java.awt.Font("SF Pro Text", 0, 24)); // NOI18N
        orderCompleteButton.setForeground(new java.awt.Color(255, 255, 255));
        orderCompleteButton.setText("Order Completed");
        orderCompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCompleteButtonActionPerformed(evt);
            }
        });
        mainPanel.add(orderCompleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 220, 60));

        pendingOrdersLabel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        pendingOrdersLabel.setForeground(new java.awt.Color(242, 242, 242));
        pendingOrdersLabel.setText("Pending Orders:");
        mainPanel.add(pendingOrdersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

        timeLabel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(242, 242, 242));
        timeLabel.setText("Time:");
        mainPanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        datetimeTF.setEditable(false);
        datetimeTF.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        datetimeTF.setForeground(new java.awt.Color(0, 0, 51));
        datetimeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datetimeTF.setEnabled(false);
        datetimeTF.setFocusable(false);
        datetimeTF.setRequestFocusEnabled(false);
        datetimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetimeTFActionPerformed(evt);
            }
        });
        mainPanel.add(datetimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/General/wood final.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ManagerHome mgrHome = new ManagerHome(mgr.getUserID(), mgr.getUserPassword());
        mgrHome.setVisible(true);
        this.dispose();
        try {
            Logger.info("ManageOrder","Manager " + mgr.getUserID() + " has attempted to view Manager Home page.");
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(ManagerManageOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void datetimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetimeTFActionPerformed

    }//GEN-LAST:event_datetimeTFActionPerformed

    private void pendingOrdersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingOrdersTableMouseClicked

    }//GEN-LAST:event_pendingOrdersTableMouseClicked

    private void orderCompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCompleteButtonActionPerformed
        DefaultTableModel POTableModel = (DefaultTableModel) pendingOrdersTable.getModel();
        File POFile = new File(POFILE);
        
        if (pendingOrdersTable.getSelectedRowCount() >= 1) {
            
            int row = pendingOrdersTable.getSelectedRow();
            Object[] section = new Object[6];

            // Getting the data from pendingOrdersTable
            for (int col = 0; col < POTableModel.getColumnCount(); col++) {
                section[col] = POTableModel.getValueAt(row,col);
            }

            String orderID = String.valueOf(section[0]);
            String foodID = String.valueOf(section[2]);

            // Remove the line in pendingOrders.txt
            FileHandling fh = new FileHandling();
            fh.removeLine(POFile, 0, 2, orderID, foodID);

            try {
                // Add the line to completedOrders.txt
                File COFile = new File(COFILE);
                String fileData = section[0] + "|" + section[1] + "|" + section[2] + "|" + section[3] + "|" + section[4] + "|" + section[5];
                fh.appendToFile(fileData, COFile);
            } catch (IOException e) {
                try {
                    Logger.error("ManageOrder","Exception occurred - " + e.toString());
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(ManagerManageOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
                throw new IllegalArgumentException("File does not exist!");
            }

            try {
                // Reloading the table
                loadMenu();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(ManagerManageOrder.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Order ID " + orderID + " with Food ID " + foodID + " has been marked as completed!");
            try {
                Logger.info("ManageOrder","Order ID " + orderID + " with Food ID " + foodID + " has been marked as completed by Manager " + mgr.getUserID() + ".");
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(ManagerManageOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (pendingOrdersTable.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Table is empty!");
        } else {
            JOptionPane.showMessageDialog(null, "No row is selected for completion!");
        }
    }//GEN-LAST:event_orderCompleteButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField datetimeTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton orderCompleteButton;
    private javax.swing.JLabel pendingOrdersLabel;
    private javax.swing.JTable pendingOrdersTable;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel userDisplayLabel;
    private javax.swing.JLabel userIDTF;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    
}
